CREATE TABLE MARKETS (
  market_id     NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome          VARCHAR2(100) NOT NULL,
  tipo          VARCHAR2(10)  CHECK (tipo IN ('ATACADO','VAREJO'))
);

CREATE TABLE PRODUCTS (
  product_id    NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  codigo        VARCHAR2(20) UNIQUE NOT NULL,
  nome          VARCHAR2(100) NOT NULL,
  categoria     VARCHAR2(50)
);

CREATE TABLE PRICES (
  price_id      NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  data_ref      DATE NOT NULL,
  product_id    NUMBER NOT NULL REFERENCES PRODUCTS(product_id),
  market_id     NUMBER NOT NULL REFERENCES MARKETS(market_id),
  tipo_preco    VARCHAR2(15) CHECK (tipo_preco IN ('ATACADO_MIN','ATACADO_MED','ATACADO_MAX','VAREJO')),
  unidade_orig  VARCHAR2(20),
  preco_orig    NUMBER(12,2) CHECK (preco_orig > 0),
  preco_kg      NUMBER(12,4) CHECK (preco_kg  > 0),
  fonte         VARCHAR2(40),
  CONSTRAINT uq_price UNIQUE (data_ref, product_id, market_id, tipo_preco)
);

CREATE INDEX idx_prices_produto_data ON PRICES (product_id, data_ref);
CREATE INDEX idx_prices_mercado_data ON PRICES (market_id, data_ref);
CREATE INDEX idx_prices_tipo ON PRICES (tipo_preco);

CREATE OR REPLACE VIEW VW_PRICES_RECENTES AS
SELECT p.codigo,
       p.nome,
       m.nome AS mercado,
       pr.tipo_preco,
       pr.data_ref,
       pr.preco_kg,
       pr.preco_orig,
       pr.unidade_orig,
       pr.fonte
  FROM PRICES pr
  JOIN PRODUCTS p ON p.product_id = pr.product_id
  JOIN MARKETS  m ON m.market_id = pr.market_id
 WHERE pr.data_ref >= TRUNC(SYSDATE) - 30;
